{{- if .Values.ingress.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-auth-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /auth
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-notification-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /notification
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-nanopass-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /nanopass
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-gradegetter-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - /gradegetter
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.hostname }}`) && PathPrefix(`/auth/`)
      kind: Rule
      middlewares:
        - name: strip-auth-prefix
      services:
        - name: auth-backend
          port: 3000
    - match: Host(`{{ .Values.ingress.hostname }}`) && PathPrefix(`/gradegetter/`)
      kind: Rule
      middlewares:
        - name: strip-gradegetter-prefix
      services:
        - name: gradegetter-backend
          port: 3002
    - match: Host(`{{ .Values.ingress.hostname }}`) && PathPrefix(`/notification/`)
      kind: Rule
      middlewares:
        - name: strip-notification-prefix
      services:
        - name: notification-backend
          port: 3003
    - match: Host(`{{ .Values.ingress.hostname }}`) && PathPrefix(`/nanopass/`)
      kind: Rule
      middlewares:
        - name: strip-nanopass-prefix
      services:
        - name: nanopass-backend
          port: 3004
  tls:
    secretName: {{ .Values.ingress.tlsSecret }}
{{- end }}
